#!/usr/bin/env python3
import click

from infra.api_client.pod_manager import PodManager
from infra.api_client.network_volume_manager import NetworkVolumeManager

DEFAULT_CONFIG_DIR = "infra/configs"


@click.group()
@click.option(
    "--config-dir",
    default=DEFAULT_CONFIG_DIR,
    show_default=True,
    help="Directory containing config files",
)
@click.pass_context
def cli(ctx, config_dir):
    """RunPod infrastructure management CLI"""
    ctx.ensure_object(dict)
    ctx.obj["config_dir"] = config_dir


@cli.group()
def pod():
    """Manage pods"""


@pod.command("create")
@click.argument("pod_name")
@click.pass_context
def pod_create(ctx, pod_name):
    """Create a pod from config"""
    manager = PodManager(ctx.obj["config_dir"])
    pod_id = manager.create_from_config(pod_name)
    click.echo(f"Pod created with ID: {pod_id}")


@pod.command("status")
@click.argument("pod_id")
@click.pass_context
def pod_status(ctx, pod_id):
    """Get pod status"""
    manager = PodManager(ctx.obj["config_dir"])
    click.echo(f"Pod status: {manager.status(pod_id)}")


@pod.command("list")
@click.pass_context
def pod_list(ctx):
    """List all pods"""
    manager = PodManager(ctx.obj["config_dir"])
    click.echo(f"Pods: {manager.client.list_pods()}")


@pod.command("delete")
@click.argument("pod_id")
@click.pass_context
def pod_delete(ctx, pod_id):
    """Delete a pod"""
    manager = PodManager(ctx.obj["config_dir"])
    manager.client.delete_pod(pod_id)
    click.echo(f"Pod deleted: {pod_id}")


@cli.group()
def volume():
    """Manage network volumes"""


@volume.command("create")
@click.argument("filename", default="network_volume.yaml")
@click.pass_context
def volume_create(ctx, filename):
    """Create a network volume from config"""
    manager = NetworkVolumeManager(ctx.obj["config_dir"])
    volume_id = manager.create_from_config(filename)
    click.echo(f"Network volume created with ID: {volume_id}")


@volume.command("status")
@click.argument("volume_id")
@click.pass_context
def volume_status(ctx, volume_id):
    """Get network volume status"""
    manager = NetworkVolumeManager(ctx.obj["config_dir"])
    click.echo(f"Network volume status: {manager.status(volume_id)}")


@volume.command("list")
@click.pass_context
def volume_list(ctx):
    """List all network volumes"""
    manager = NetworkVolumeManager(ctx.obj["config_dir"])
    click.echo(f"Network volumes: {manager.client.list_network_volumes()}")


@volume.command("delete")
@click.argument("volume_id")
@click.pass_context
def volume_delete(ctx, volume_id):
    """Delete a network volume"""
    manager = NetworkVolumeManager(ctx.obj["config_dir"])
    manager.client.delete_network_volume(volume_id)
    click.echo(f"Network volume deleted: {volume_id}")


if __name__ == "__main__":
    cli()
