admin:
  image: "runpod/base:1.0.2-ubuntu2404"
  name: "microstructure-admin"
  disk: 10
  cloud: SECURE
  env:
    JUPYTER_PASSWORD: ""
    PUBLIC_KEY: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILbRau3oKACgYPcJzeQ6CnDzGTLTfqazHLxwjJWpveep throwaway@vivobook-2025-04-24"
  ports:
    - 22/tcp
  mounts:
    network:
      - volumeId: "z7uhknufcb"
        path: "/workspace"
  dataCenterIds:
    - "EUR-IS-1"
  cpu:
    id: "cpu3c"
    vcpuCount: 2

classification_1:
  name: "microstructure-classification_1-training"
  image: "michaelschott00/microstructures:main"
  args: "./tune_classification_1.sh"
  cloud: SECURE
  env:
    JUPYTER_PASSWORD: ""
    PUBLIC_KEY: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILbRau3oKACgYPcJzeQ6CnDzGTLTfqazHLxwjJWpveep throwaway@vivobook-2025-04-24"
  ports:
    - 22/tcp
  dataCenterIds:
    - "EUR-IS-1"
  mounts:
    network:
      - volumeId: "z7uhknufcb"
        path: "/workspace"
  gpu:
    id: "NVIDIA RTX 2000 Ada Generation"
    count: 1
  disk: 30
